### ISSUE TITLE
Global is not defined

### ISSUE THREAD

**Issue by resoursa** [universal-tilt-js/universal-tilt.js#11]
HI, i have added universal-tilt.min.js but it says `Uncaught ReferenceError: global is not defined
    at universal-tilt.min.js:1`

i have use jQuery v3.3.1. Can you help please?

**Comment by resoursa** [comment]
OK, i have figure out that is a node component, but maybe you can provide compiled script. That i can use it just as jQuery plugin?

**Comment by JB1905** [comment]
I will look at the problem next week

**Comment by JB1905** [comment]
I changed the value of globalObject (now it's window or global) in 2a0ef04. This should solve the problem.
The changes will be added in 2.0.0 beta 3 and 1.2.2 soon.
