### ISSUE TITLE
UniversalTilt is not a constructor

### ISSUE THREAD

**Issue by vstrelianyi** [universal-tilt-js/universal-tilt.js#14]
Receiving an error  - 
"Uncaught TypeError: UniversalTilt is not a constructor "
when using VanillaJs approach
// v1
const tilt = new UniversalTilt(elems, {
  // options...
});

**Comment by JB1905** [comment]
I will look at the problem today.
I need information about which version of the library you use and whether you use ES6 import or CDN.

**Comment by vstrelianyi** [comment]
Hi Jakub!

I have used the version 2.0.0. Tried both :

**Comment by vstrelianyi** [comment]
Hi Jakub!

I have used the version 2.0.0. Tried both :
-Cdn from www.jsdelivr.com/
and via script html tag, ( lib taken from https://github.com/JB1905/universal-tilt.js )

**Comment by JB1905** [comment]
OK, Thanks!

**Comment by JB1905** [comment]
Check this:
https://cdn.jsdelivr.net/npm/universal-tilt.js@1.2.4/

**Comment by vstrelianyi** [comment]
Should I take the latest version 2.0.3 ? you sent link to 1.2.4

**Comment by JB1905** [comment]
Yes because this is configuration for v1.x.x not v2.x.x

> Receiving an error -
> "Uncaught TypeError: UniversalTilt is not a constructor "
> when using VanillaJs approach
> // v1
> const tilt = new UniversalTilt(elems, {
> // options...
> });

**Comment by vstrelianyi** [comment]
Ok, clear , thx
