### ISSUE TITLE
Uncaught TypeError: UniversalTilt.init is not a function 

### ISSUE THREAD

**Issue by vstrelianyi** [universal-tilt-js/universal-tilt.js#15]
Receiving an error  - 
" Uncaught TypeError: UniversalTilt.init is not a function "
when using this approach - 
// v2
const tilt = UniversalTilt.init({
  elements: elems,
  settings: {
    // options...
  },
  callbacks: {
    // callbacks...
  }
});

**Comment by JB1905** [comment]
I will look at the problem this week.
I need information about which version of the library you use and whether you use ES6 import or CDN.

**Comment by JB1905** [comment]
I probably found a problem. Webpack sets UniversalTilt as a namespace and the main class as default.
Now without ES6 import you need to set `UniversalTilt.default.init({ ... })`.
I will issue a patch this week.
Thanks!

**Comment by vstrelianyi** [comment]
thx man! you are doing a great job by continuing to develop this library!

**Comment by JB1905** [comment]
Check this update:
https://cdn.jsdelivr.net/npm/universal-tilt.js@2.0.1/

**Comment by vstrelianyi** [comment]
issue fixed ! thx

**Comment by vstrelianyi** [comment]
btw,
I have checked the first method

// v1const tilt = new UniversalTilt(elems, {
  // options...
});


and have received the following error in console -
" this.element.getAttribute is not a function "

Regards,
Viktor

**Comment by JB1905** [comment]
I will look at it
