### ISSUE TITLE
Data exclude /(iPod|iPhone|iPad|Android)/ not working

### ISSUE THREAD

**Issue by AdaptCharm** [universal-tilt-js/universal-tilt.js#38]
For some reason the /(iPod|iPhone|iPad|Android)/ data exclude won't work. On desktop in looks fine, however, on mobile phones it looks weird as hell.

My website: https://casinoxbonuses.com/

**Comment by JB1905** [comment]
Hi!
I know where the problem is and I will try to fix it tomorrow.
I need to add additional checks for navigator user agent.

**Comment by AdaptCharm** [comment]
> Hi!
> I know where the problem is and I will try to fix it tomorrow.
> I need to add additional checks for navigator user agent.

Hi, did you fix the issues yet?

Thanks in advance.

**Comment by JB1905** [comment]
Hi!
Update will be available later today or tomorrow.

**Comment by JB1905** [comment]
v2.0.5 (v2.0.4) probably fixes this bug

**Comment by AdaptCharm** [comment]
> v2.0.5 (v2.0.4) probably fixes this bug

The bug on mobile devices is fixed, however, there is a new bug. If you navigate once again to my site https://casinoxbonuses.com/ you'll see that the boxes won't follow your mouse on hover. It just zooms in and out, no tilt effect.

**Comment by JB1905** [comment]
I added an external library (`platform`). If you use npm or yarn it is installed automatically. If you use CDN, you must add the script `https://cdn.jsdelivr.net/npm/platform@1.3.5/platform.min.js` before attaching universal-tilt.js. I will try to solve this better in the next updates.

**Comment by AdaptCharm** [comment]
> I added an external library (`platform`). If you use npm or yarn it is installed automatically. If you use CDN, you must add the script `https://cdn.jsdelivr.net/npm/platform@1.3.5/platform.min.js` before attaching universal-tilt.js. I will try to solve this better in the next updates.

For some reason that lib wouldn't be included through CDN. Any possibility you can permanently fix this without including that library?

**Comment by TemaSM** [comment]
@JB1905 
> v2.0.5 (v2.0.4) probably fixes this bug

Btw it probably produces a bug, when `base` option is set. With 2.0.3 and `base` works just fine.
![image](https://user-images.githubusercontent.com/5501615/59495191-74112f80-8e97-11e9-884d-adb27eb7dbc0.png)
Problem is here:
![image](https://user-images.githubusercontent.com/5501615/59495229-9014d100-8e97-11e9-909b-db31e8935363.png)

**Comment by JB1905** [comment]
Tomorrow I will release new version with built-in `platform` library
